name: Renew Certbot Certificates

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 1 * *' # This will run at 00:00 on the first day of every month 

jobs:
  renew-certs:
    runs-on: ["self-hosted","ub22"]    
    
    steps: 

    - name: Running as user
      run: |
        echo $(whoami)@$(hostname)

    - name: Certbot version
      run: |
        certbot --version        

    - name: Checkout repo 
      uses: actions/checkout@v2 

    - name: Certbot Renew certificates
      run: |
        # Assuming the sysadmin user has the necessary permissions
        sudo certbot renew --non-interactive --quiet

        echo "SUCCESS: Certbot renewed all certs successfully."

    - name: Restart Nginx         
      run: |
        echo "Restarting nginx web service and reverse proxy"
        sudo systemctl restart nginx 

        sudo systemctl status nginx 

    - name: Restart NodeJS Javascript game Fruitfall
      run: |
        echo "Restarting NodeJS app using PM2"        
        pm2 start fruitfall 

        pm2 list 

