name: Renew Certbot Certificates

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 1 * *' # This will run at 00:00 on the first day of every month 

jobs:
  renew-certs:
    runs-on: ["self-hosted","ub22"]    
    
    steps: 

    - name: Running as user
      run: |
        echo $(whoami)@$(hostname)

    - name: Certbot version
      run: |
        certbot --version        

    - name: Checkout repo 
      uses: actions/checkout@v2 

    # - name: Install SSH Key
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa

    # - name: Renew certificates
    #   run: |
    #     # Assuming the sysadmin user has the necessary permissions
    #     ssh -o StrictHostKeyChecking=no sysadmin@yourserver.com "certbot renew --non-interactive --quiet"

    # - name: Cleanup SSH key
    #   run: rm -f ~/.ssh/id_rsa