name: Renew Certbot Certificates

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 1 * *' # This will run at 00:00 on the first day of every month 
    - cron: '0 12 * * *' # This will run at 12:00 every day

jobs:
  renew-certs:
    runs-on: ["self-hosted","ub22"]    
    
    steps: 

    - name: Running as user
      run: |
        echo $(whoami)@$(hostname)

    - name: Certbot version
      run: |
        certbot --version        

    - name: Checkout repo 
      uses: actions/checkout@v2 

    - name: Certbot Renew certificates
      run: |
        # Run Certbot and capture the output 
        output=$(sudo certbot renew --non-interactive --agree-tos -m thecodemountains@gmail.com 2>&1)

        # Check if certs were renewed 
        if echo "$output" | grep -q "Congratulations"; then 
          echo "SUCCESS: Certbot renewed all certs successfully."          
        elif echo "$output" | grep -q "No renewals were attempted"; then
          echo "SKIPPING: Certificates not yet due for renewal."
        else
          echo "ERROR: An unexpected situation occurred."
          echo "$output"
        fi


    - name: Restart Nginx         
      run: |
        echo "Restarting nginx web service and reverse proxy"
        sudo systemctl restart nginx 

        sudo systemctl status nginx 

    - name: Restart NodeJS Javascript game Fruitfall
      run: |
        echo "Restarting NodeJS app using PM2"        
        pm2 start fruitfall 

